name: vijay-webapp python testing
# Trigger
on:
  push:
    branches:
      - "main"

# jobs for performing operations
jobs:
  python_testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]  
    steps:
      - name: Checking python version on platform ${{ matrix.os }}
        run: python -V

      - name: fetching git repo code to runners machine
        uses: actions/checkout@v4
        
      - name: lets run python code on machine ${{ matrix.os }}
        run: python vijay.py  