name: vijay-webapp python testing
# Trigger
on:
  push:
    branches:
      - "main"

# jobs for performing operations
jobs:
  python_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checking python version on platform
        run: python -V